### ISSUE TITLE
building with rdmd fails

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/Digger#41] opened 2016-09-09 10:47 UTC
```
% rdmd --build-only digger                                   
Undefined symbols for architecture x86_64:
  "_D2ae5utils4sini63__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager3DMD6ConfigZ14makeIniHandlerFNaNbNfKS2ae3sys1d7manager8DManager3DMD6ConfigZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler", referenced from:
      _D2ae5utils4sini77__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ14makeIniHandlerFKS2ae3sys1d7manager8DManager6Config5Build10ComponentsZ12__dgliteral3MFNaNfAyaZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler in digger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1
```

this is with dmd 2.071.2-b3 on OS X

building with dub works fine

**Comment by CyberShadow** [comment] 2016-09-09 22:21
Duplicate of #37.

**Closed by CyberShadow** 2016-09-09 22:21 UTC
