### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/Digger#43] opened 2016-09-29 16:58 UTC
```
git clone --recursive https://github.com/CyberShadow/Digger
cd Digger
rdmd --build-only digger
```

```
Undefined symbols for architecture x86_64:
  "_D2ae5utils4sini63__T14makeIniHandlerTAyaTS2ae3sys1d7manager8DManager3DMD6ConfigZ14makeIniHandlerFNaNbNfKS2ae3sys1d7manager8DManager3DMD6ConfigZS2ae5utils4sini30__T20IniTraversingHandlerTAyaZ20IniTraversingHandler", referenced from:
```

**Comment by CyberShadow** [comment] 2016-09-29 16:59
Duplicate of #37.

**Closed by CyberShadow** 2016-09-29 16:59 UTC
