### ISSUE TITLE
OSX / Digger / Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Robert-M-Muench** [CyberShadow/Digger#65] opened 2018-02-24 14:43 UTC
```
imac-pro-1:Digger robby$ rdmd --build-only digger
Undefined symbols for architecture x86_64:
  "_D2ae5utils4sini__T14makeIniHandlerTAyaTSQBn3sys1d7manager8DManager3DMD6ConfigZQCiFNaNbNfKQByZSQDpQDpQDm__T20IniTraversingHandlerTQDqZQBb", referenced from:
      _D2ae5utils4sini__T14makeIniHandlerTAyaTSQBn3sys1d7manager8DManager6Config5Build10ComponentsZQCwFKQCgZ12__dgliteral3MFNaNfQDiZSQEvQEvQEs__T20IniTraversingHandlerTQEwZQBb in digger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
imac-pro-1:Digger robby$
```

**Comment by CyberShadow** [comment] 2018-02-24 16:25
Duplicate of #37.

**Closed by CyberShadow** 2018-02-24 16:25 UTC
